apiVersion: v1
kind: Secret
metadata:
  name: cezzis-com-local-bootstrapper-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
type: Opaque
data:
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure-blob.azure-platform.svc.cluster.local:10000/devstoreaccount1;"
  COSMOSDB_ACCOUNT_KEY: "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
  OTEL_OTLP_AUTH_HEADER: "Bearer bd97d99d-f52d-4827-84d5-3760cbc2c8ea"
  RABBITMQ_ADMIN_PASSWORD: "password"
  RABBITMQ_APP_PASSWORD: "N+suCeoERK&yhso9Nbq1Z-5X"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cezzis-com-local-bootstrapper-config
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
data:
  ENV: "prd"
  ACCOUNT_AVATARS_CONTAINER_NAME: "account-avatars-prd"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker-1.kafka-platform.svc.cluster.local:19092"
  KAFKA_COCKTAILS_TOPIC_DEFS: "cocktails-update-topic-prd,cocktails-ingestion-extraction-results-prd,cocktails-ingestion-chunking-results-prd"
  KAFKA_DEFAULT_TOPIC_PARTITIONS: "4"
  KAFKA_SECURITY_PROTOCOL: "PLAINTEXT"
  COSMOSDB_ACCOUNT_ENDPOINT: "https://cosmosdb.azure-platform.svc.cluster.local:8081/"
  COSMOSDB_COCKTAILS_DATABASE_NAME: "cocktails-db-prd"
  COSMOSDB_COCKTAILS_CONTAINER_DEFS: "cezzis-cocktails-cocktail:/id,cezzis-cocktails-ingredient:/id,cezzis-device-auth:/id"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-platform.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "cezzis-com-bootstrapper"
  OTEL_SERVICE_NAMESPACE: "cezzis"
  RABBITMQ_VHOST: "cezzis-prd"
  RABBITMQ_HOST: "http://rabbitmq.rabbitmq-platform.svc.cluster.local"
  RABBITMQ_PORT: "5671"
  RABBITMQ_ADMIN_PORT: "15672"
  RABBITMQ_ADMIN_USERNAME: "admin"
  RABBITMQ_APP_USERNAME: "cezzis-app-user-prd"
  RABBITMQ_APP_CONFIG_FILE_PATH: "/config/rabbitmq.json"
  QDRANT_HOST: "qdrant.ai-platform.svc.cluster.local"
  QDRANT_PORT: "6333"
  QDRANT_API_KEY: ""
  QDRANT_COLLECTION_NAME: "cocktails-prd"
  QDRANT_VECTOR_SIZE: "768"
  QDRANT_USE_HTTPS: "false"