apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: cezzis-com-local-bootstrapper-updater
  namespace: cezzis
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "cezzis-com-local-bootstrapper"
      images:
        - imageName: "acrveceusgloshared001.azurecr.io/cezziscombootstrapper"
          alias: "cezziscombootstrapper"
          updateStrategy: "semver"
          versionConstraint: "0.x"
          pullSecret: "secret:argocd/acr-admin-creds#creds"
  writeBackConfig:
    method: argocd