apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: cezzis-com-local-bootstrapper-updater
  namespace: cezzis
spec:
  useAnnotations: false 
  namespace: argocd
  applicationRefs:
    - namePattern: "cezzis-com-local-bootstrapper"
      commonUpdateSettings:
        updateStrategy: "semver"
        versionConstraint: "0.x"
        pullSecret: "pullsecret:argocd/acr-pull-secret"
      images:
        - imageName: "acrveceusgloshared001.azurecr.io/cezziscombootstrapper"
          alias: "cezziscombootstrapper"
          kustomize:
            imageName: "acrveceusgloshared001.azurecr.io/cezziscombootstrapper"
  writeBackConfig:
    method: argocd