apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yml
  - rabbitmq-configmap.yml
  - cezzis-com-local-bootstrapper.yml
images:
  - name: acrveceusgloshared001.azurecr.io/cezziscombootstrapper
    newTag: 0.0.72
    newName: acrveceusgloshared001.azurecr.io/cezziscombootstrapper
