apiVersion: v1
kind: Namespace
metadata:
  name: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false